In [2]:
import scipy as sp
import pandas as pd
import numpy as np

from selenium import webdriver  
from selenium.webdriver import ActionChains as AC
from selenium.webdriver.common.keys import Keys 
import chromedriver_autoinstaller
from tqdm import tqdm
from tqdm import tqdm_notebook
import re
from time import sleep
import time
import requests
from bs4 import BeautifulSoup
%matplotlib inline
import os
import matplotlib.pyplot as plt
import seaborn as sns
import graphviz             
from sklearn.tree import export_graphviz

from konlpy.tag import Kkma       ; kkma = Kkma()
from konlpy.tag import Hannanum   ; hannanum = Hannanum()
from konlpy.tag import Okt        ; t = Okt()
from konlpy.tag import *
import pickle

# matplotlib 그래프 한글폰트 깨질 때 대처(Mac & Window)
import matplotlib
from matplotlib import font_manager, rc
import platform

if platform.system() == 'Windows':
# 윈도우인 경우
    font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
    rc('font', family=font_name)
else:    
# Mac 인 경우
    rc('font', family='AppleGothic')
    
# 그래프에서 마이너스 기호가 표시되도록 하는 설정
matplotlib.rcParams['axes.unicode_minus'] = False

# 워닝 무시
import warnings
warnings.filterwarnings('ignore')

# 크롤링

In [40]:
# 저장해둔 url 불러오기
df = pd.read_csv('오늘의집_urls.csv')
df['url']

0      https://ohou.se/productions/815721/selling?aff...
1      https://ohou.se/productions/1116934/selling?af...
2      https://ohou.se/productions/296038/selling?aff...
3      https://ohou.se/productions/986411/selling?aff...
4      https://ohou.se/productions/1106222/selling?af...
                             ...                        
515    https://ohou.se/productions/1053570/selling?af...
516    https://ohou.se/productions/1142803/selling?af...
517    https://ohou.se/productions/414537/selling?aff...
518    https://ohou.se/productions/1059384/selling?af...
519    https://ohou.se/productions/1011938/selling?af...
Name: url, Length: 520, dtype: object

In [3]:
df2 = df['url'][:500]
df2

0      https://ohou.se/productions/815721/selling?aff...
1      https://ohou.se/productions/1116934/selling?af...
2      https://ohou.se/productions/296038/selling?aff...
3      https://ohou.se/productions/986411/selling?aff...
4      https://ohou.se/productions/1106222/selling?af...
                             ...                        
495    https://ohou.se/productions/312502/selling?aff...
496    https://ohou.se/productions/861887/selling?aff...
497    https://ohou.se/productions/618662/selling?aff...
498    https://ohou.se/productions/967608/selling?aff...
499    https://ohou.se/productions/333120/selling?aff...
Name: url, Length: 500, dtype: object

In [4]:
len(df2)

500

In [5]:
dict = {}
dict1 = {}
dict2 = {} 
dict3 = {}
dict4 = {}
dict5 = {}

n = len(df2)    # 전체 수 : len(df['url'])   

for i in range(0, n):   
    try:
        chrome_path = chromedriver_autoinstaller.install()
        driver = webdriver.Chrome(chrome_path)    
        driver.get(df['url'][i])
        time.sleep(1)
        
        title_list = []
        overlays = "/html/body/div[1]/div/div[2]/div[1]/div/div[2]/div[1]/h1/div/span"
        t = driver.find_element_by_xpath(overlays).text
        title_list.append(t)
        dict[i] = title_list
        
        price_list = []
        overlays = "/html/body/div[1]/div/div[2]/div[1]/div/div[2]/div[1]/div[1]/div/span[1]/span[3]"
        price = driver.find_element_by_xpath(overlays).text
        if '원' in price:
            price = price.replace('원','')
        else:
            pass
        price_list.append(price)
        dict1[i] = price_list
        
        rating_list = []
        overlays = "/html/body/div[1]/div/div[2]/div[5]/div/div[1]/div/section[2]/div/div[1]/div/div[1]"
        rating = driver.find_element_by_xpath(overlays).text
        rating_list.append(rating)
        dict2[i] = rating_list
        
        review_num = []
        overlays = "/html/body/div[1]/div/div[2]/div[1]/div/div[2]/div[1]/div[1]/p/a"
        review_n = driver.find_element_by_xpath(overlays).text
        if '개 리뷰' in review_n:
            review_n = review_n.replace('개 리뷰','')
        else:
            pass
        review_num.append(review_n)
        dict3[i] = review_num
        
        comment_list = []
        overlay1 = "/html/body/div[1]/div/div[2]/div[5]/div/div[1]/div/section[2]/div/div[3]/div[1]/article/p"
        comment = driver.find_element_by_xpath(overlay1).text
        comment_list.append(comment)
        dict4[i] = comment_list
        
        material_list = []
        overlays = "/html/body/div[1]/div/div[2]/div[5]/div/div[1]/div/section[1]/div/table/tbody/tr[1]/td"
        material = driver.find_element_by_xpath(overlays)
        material = material.text
        if '원단:' in title:
            title = title.replace('원단:','')
        if '충전재:' in title:
            title = title.replace('충전재:','')
        else:
            pass
        material_list.append(material)
        dict5[i] = material_list
        
        driver.close()
       
        
    except:
        driver.quit()
        continue
        


In [6]:
dict

{0: ['[단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트'],
 1: ['따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm'],
 2: ['멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors'],
 3: ['데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors'],
 4: ['마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종'],
 5: ['침대 시트 매트리스 커버 이불 쇼파 패드 고정 집게 클립 2P'],
 6: ['양말부터 수건 옷 이불까지 고정력 강력한 스테인리스 빨래집게 5종'],
 7: ['트윈체크 항균 알러지케어 사계절 차렵이불세트 2size 3colors'],
 8: ['내츄럴 광목 프릴 워싱 침대스커트(SS/Q/K)'],
 9: ['(60수면100%)특급호텔 납품 솔리드 이불커버 SS/Q/K 6컬러'],
 10: ['(한파용/세트)특급호텔 납품 구스충전재100% 이불+솔리드 이불커버'],
 11: ['600D 옥스포드 튼튼한 이불 보관함 3size 2colors'],
 12: ['(당일발송) 따뜻한 1인용 수술블랭킷 쇼파 침대 무릎 담요'],
 13: ['모네 100수 고밀도 피그먼트 이불커버세트 (S/QK겸용) 4colors'],
 14: ['기습한파 극세사 침구 풀세트(이불+패드+베개) Q 5종 시즌오프'],
 15: ['구스이불처럼 포근한 워셔블 이불솜 3size'],
 16: ['600D 옥스퍼드 이불정리함 이불가방 방수가방 시리즈'],
 17: ['[리퍼] 가을 겨울 감성 차박 캠핑 경량 이불 (2colors)'],
 18: ['먼지없는 알러지케어 항균 기능성 빌리프 차렵이불(SS/Q) 4컬러'],
 19: ['(당일발송)그린패턴대형 블랭킷 거실 쇼파 침대스프레드겸 무릎담요'],
 20: ['유기농 오가닉 100% 라인 순면 옥수수솜 차렵이불세트(SS/Q&K)-2color'],
 21: ['프리미엄화이바 데이나잇 차렵이불/세트/러그/매트리스커

In [23]:
from pandas import Series, DataFrame
df = DataFrame(dict)
title_df = df.T
title_df = title_df.rename(columns={0:'title'})
title_df

title
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종
..                                              ...
495                     클라우드 60수광목 차렵이불(세트) 2colors
496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color
497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors
498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors
499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors

[497 rows x 1 columns]

In [26]:
df1 = DataFrame(dict1)
price_df = df1.T
price_df = price_df.rename(columns={0:'price'})
price_df

price
0    29,900
1    18,900
2    15,900
3    19,900
5     1,800
..      ...
495  49,900
496   4,500
497  38,400
498  29,900
499  29,900

[447 rows x 1 columns]

In [27]:
df2 = DataFrame(dict2)
rating_df = df2.T
rating_df = rating_df.rename(columns={0:'rating'})
rating_df

rating
0      4.7
1      5.0
2      4.7
3      4.9
5      4.6
..     ...
495    4.6
496    4.5
497    4.9
498    4.7
499    4.8

[429 rows x 1 columns]

In [28]:
df3 = DataFrame(dict3)
review_num_df = df3.T
review_num_df = review_num_df.rename(columns={0:'review_num'})
review_num_df

review_num
0          275
1           13
2          425
3           16
5          560
..         ...
495      2,804
496         26
497         34
498         11
499        452

[429 rows x 1 columns]

In [29]:
df4 = DataFrame(dict4)
comment_df = df4.T
comment_df = comment_df.rename(columns={0:'comment'})
comment_df

comment
0             택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….
1                            배송도 빠르고 너무 예뻐요 다른것도 사고싶어요
2                     여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.
3       이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥
5                              있으니까 훨씬 좋네요 진작 살 걸 그랬어요
..                                                 ...
495         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데
496  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...
497  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...
498  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...
499  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...

[429 rows x 1 columns]

In [37]:
import pandas as pd
df = pd.concat((title_df, price_df), sort=True, axis = 1)
df = pd.concat((df,rating_df ), sort=True, axis = 1)
df= pd.concat((df,review_num_df), sort=True, axis = 1)
df= pd.concat((df,comment_df ), sort=True, axis = 1)
df

title   price rating review_num  \
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900    4.7        275   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900    5.0         13   
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900    4.7        425   
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900    4.9         16   
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종     NaN    NaN        NaN   
..                                              ...     ...    ...        ...   
495                     클라우드 60수광목 차렵이불(세트) 2colors  49,900    4.6      2,804   
496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500    4.5         26   
497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400    4.9         34   
498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900    4.7         11   
499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900    4.8        452   

                                               comment  
0             택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….  
1                            배송도 빠르고 너무 예뻐요 다른것도 사고싶어요  
2                     여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.  
3       이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥  
4                                                  NaN  
..                                                 ...  
495         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데  
496  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...  
497  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...  
498  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...  
499  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...  

[497 rows x 5 columns]

In [38]:
df.to_csv('오늘의집.csv')

## 원단

In [3]:
# 저장해둔 url 불러오기
df = pd.read_csv('오늘의집_urls.csv')
df['url']
df2 = df['url'][:500]
df2

0      https://ohou.se/productions/815721/selling?aff...
1      https://ohou.se/productions/1116934/selling?af...
2      https://ohou.se/productions/296038/selling?aff...
3      https://ohou.se/productions/986411/selling?aff...
4      https://ohou.se/productions/1106222/selling?af...
                             ...                        
515    https://ohou.se/productions/1053570/selling?af...
516    https://ohou.se/productions/1142803/selling?af...
517    https://ohou.se/productions/414537/selling?aff...
518    https://ohou.se/productions/1059384/selling?af...
519    https://ohou.se/productions/1011938/selling?af...
Name: url, Length: 520, dtype: object

In [4]:
df2 = df['url'][367:500]
df2

367    https://ohou.se/productions/1150631/selling?af...
368    https://ohou.se/productions/968027/selling?aff...
369    https://ohou.se/productions/660500/selling?aff...
370    https://ohou.se/productions/685726/selling?aff...
371    https://ohou.se/productions/204722/selling?aff...
                             ...                        
495    https://ohou.se/productions/312502/selling?aff...
496    https://ohou.se/productions/861887/selling?aff...
497    https://ohou.se/productions/618662/selling?aff...
498    https://ohou.se/productions/967608/selling?aff...
499    https://ohou.se/productions/333120/selling?aff...
Name: url, Length: 133, dtype: object

In [5]:
dict5 ={}

n = len(df2)    # 전체 수 : len(df['url'])   

for i in range(0, n):   
    try:
        chrome_path = chromedriver_autoinstaller.install()
        driver = webdriver.Chrome(chrome_path)    
        driver.get(df['url'][i+366])
        time.sleep(1)
        
        material_list = []
        overlays = "/html/body/div[1]/div/div[2]/div[5]/div/div[1]/div/section[1]/div/table/tbody/tr[1]/td"
        material = driver.find_element_by_xpath(overlays)
        material = material.text
        material_list.append(material)
        dict5[i+366] = material_list
        
        
        driver.close()
       
        
    except:
        driver.close()
        continue
        

In [6]:
dict5

{366: ['상세페이지 참조'],
 368: ['침대패드 - 겉면: 폴리에스터 87% + 나일론 13%'],
 369: ['패브릭 이불 보관가방 정리함'],
 371: ['그린노트체크 자체제작 3size 사계절이불세트'],
 372: ['순면100%'],
 373: ['겉감:폴리에스터 100%\n충전재:폴리에스터 100%'],
 374: ['상세페이지 참조'],
 375: ['상세페이지참조'],
 377: ['상세페이지참고'],
 378: ['상세페이지 참조'],
 379: ['상품상세설명 참고'],
 380: ['순면 60수 피그먼트 워싱면'],
 381: ['앞 : 세미화이바 피치 스킨 (폴리에스터 100%), 뒤 : 마이크로화이바 (극세사)FUR (폴리에스터 100%)'],
 382: ['상세페이지참고'],
 384: ['겉감- 면 100%(60수 아사) / 충전재- 폴리에스터 100%'],
 385: ['상세페이지 참조'],
 386: ['충전재 : Conjugate Fiber'],
 387: ['앞:마이크로모달50%+면50%\n뒤:마이크로화이바 극세사 FUR\n충전재:마이크로화이바솜'],
 388: ['겉감 : 울트라파인화이바 (폴리에스터 100%)\n충전재 : 고급이불솜 (폴리에스터 100%)'],
 391: ['60수 고밀도 순면(바이오워싱)(면 100%)'],
 392: ['옥스펀드언더베드수납함'],
 393: ['폴리에스터100%'],
 394: ['원단:모이스처 컨트롤 고밀도 면 100%\n충전재:친환경 옥수수솜'],
 395: ['오페 키큰장 슬라이딩 미니 이불 옷장 800'],
 396: ['이불/베개커버/패드 : 고밀도 60수 순면\n매트리스커버 : 40수 트윌 순면'],
 397: ['이불정리함'],
 398: ['플란넬 + 양털극세사 (폴리에스테르 100%)'],
 400: ['상세페이지 참조'],
 401: ['나노화이바(폴리에스터100%)/충전재:훼더솜(폴리에스터100%)'],
 402: ['세미 나노화이바(폴리에스테르100%)

In [8]:
from pandas import Series, DataFrame
df5 = DataFrame(dict5)
materiall_df = df5.T
materiall_df = materiall_df.rename(columns={0:'material'})
materiall_df
materiall_df.to_csv('오늘의집material.csv')

In [58]:
# 저장해둔 url 불러오기
dff = pd.read_csv('오늘의집.csv')
dff

Unnamed: 0                                           title   price  \
0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900   
1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900   
2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900   
3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900   
4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종     NaN   
..          ...                                             ...     ...   
492         495                     클라우드 60수광목 차렵이불(세트) 2colors  49,900   
493         496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500   
494         497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400   
495         498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900   
496         499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900   

     rating review_num                                            comment  
0       4.7        275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….  
1       5.0         13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요  
2       4.7        425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.  
3       4.9         16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥  
4       NaN        NaN                                                NaN  
..      ...        ...                                                ...  
492     4.6      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데  
493     4.5         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...  
494     4.9         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...  
495     4.7         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...  
496     4.8        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...  

[497 rows x 6 columns]

In [59]:
dfff= pd.concat((dff,material_df), sort=True, axis = 1)
dfff

Unnamed: 0                                           title   price  \
0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900   
1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900   
2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900   
3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900   
4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종     NaN   
..          ...                                             ...     ...   
492         495                     클라우드 60수광목 차렵이불(세트) 2colors  49,900   
493         496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500   
494         497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400   
495         498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900   
496         499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900   

     rating review_num                                            comment  \
0       4.7        275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1       5.0         13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2       4.7        425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3       4.9         16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4       NaN        NaN                                                NaN   
..      ...        ...                                                ...   
492     4.6      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
493     4.5         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
494     4.9         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
495     4.7         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
496     4.8        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  
0                    40수 트윌면(Cotton 100%)  
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷  
2                                 상세페이지참고  
3                                 상세페이지참조  
4                                     NaN  
..                                    ...  
492                                   NaN  
493                                   NaN  
494                                   NaN  
495                                   NaN  
496                                   NaN  

[497 rows x 7 columns]

In [60]:
dfff.to_csv('오늘의집.csv')

In [55]:
# 저장해둔 url 불러오기
df =  pd.read_csv('오늘의집.csv')
df1 =  pd.read_csv('오늘의집material.csv')


In [53]:
df = df.drop(['Unnamed: 0.1', 'title','price','rating', 'review_num', 'comment'],axis=1)
df = df[:367]

In [54]:
dffffff=pd.concat([df,df1], axis =0)
dffffff

Unnamed: 0                              material
0             0                  40수 트윌면(Cotton 100%)
1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷
2             2                               상세페이지참고
3             3                               상세페이지참조
4             4                                   NaN
..          ...                                   ...
114         494                              상세페이지 참고
115         495                               상세페이지참조
116         496                               상세페이지참조
117         497                             폴리에스터100%
118         498                               상세페이지참조

[486 rows x 2 columns]

In [56]:
df = df.drop('material', axis =1)
df

Unnamed: 0  Unnamed: 0.1                                           title  \
0             0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트   
1             1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm   
2             2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors   
3             3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors   
4             4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종   
..          ...           ...                                             ...   
492         492           495                     클라우드 60수광목 차렵이불(세트) 2colors   
493         493           496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   
494         494           497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors   
495         495           498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors   
496         496           499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors   

      price  rating review_num  \
0    29,900     4.7        275   
1    18,900     5.0         13   
2    15,900     4.7        425   
3    19,900     4.9         16   
4       NaN     NaN        NaN   
..      ...     ...        ...   
492  49,900     4.6      2,804   
493   4,500     4.5         26   
494  38,400     4.9         34   
495  29,900     4.7         11   
496  29,900     4.8        452   

                                               comment  
0             택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….  
1                            배송도 빠르고 너무 예뻐요 다른것도 사고싶어요  
2                     여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.  
3       이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥  
4                                                  NaN  
..                                                 ...  
492         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데  
493  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...  
494  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...  
495  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...  
496  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...  

[497 rows x 7 columns]

In [57]:
dicttt= pd.merge(df,dffffff, on ='Unnamed: 0' )
dicttt

Unnamed: 0  Unnamed: 0.1                                           title  \
0             0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트   
1             1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm   
2             2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors   
3             3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors   
4             4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종   
..          ...           ...                                             ...   
479         492           495                     클라우드 60수광목 차렵이불(세트) 2colors   
480         493           496          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   
481         494           497     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors   
482         495           498       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors   
483         496           499                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors   

      price  rating review_num  \
0    29,900     4.7        275   
1    18,900     5.0         13   
2    15,900     4.7        425   
3    19,900     4.9         16   
4       NaN     NaN        NaN   
..      ...     ...        ...   
479  49,900     4.6      2,804   
480   4,500     4.5         26   
481  38,400     4.9         34   
482  29,900     4.7         11   
483  29,900     4.8        452   

                                               comment  \
0             택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1                            배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2                     여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3       이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4                                                  NaN   
..                                                 ...   
479         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  
0                    40수 트윌면(Cotton 100%)  
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷  
2                                 상세페이지참고  
3                                 상세페이지참조  
4                                     NaN  
..                                    ...  
479       겉감: 폴리에스터 100%\n충전재: 폴리에스터 100%  
480                cotton 100% 60수 고밀도 워싱  
481                              상세페이지 참고  
482                               상세페이지참조  
483                               상세페이지참조  

[484 rows x 8 columns]

In [58]:
dicttt.to_csv('오늘의집_최종전.csv')

## 색상

In [59]:
# 저장해둔 url 불러오기
df = pd.read_csv('오늘의집_urls.csv')
df['url']
df2 = df['url'][:500]
len(df2)

500

In [60]:
import re

In [61]:
dict6 ={}

n = len(df2)    # 전체 수 : len(df['url'])   

for i in range(0, n):   
    try:
        chrome_path = chromedriver_autoinstaller.install()
        driver = webdriver.Chrome(chrome_path)    
        driver.get(df['url'][i])
        time.sleep(1)
        
        color_list = []
        overlays = "form-control.empty"
        color = driver.find_element_by_class_name(overlays).text
        regex = '[가-힣]+[ ]?[가-힣]*'
        color = re.findall(regex, color)
        color_list.append(color)
        dict6[i] = color_list
        
        driver.close()
       
        
    except:
        driver.quit()
        continue
        

In [62]:
dict6

{0: [['디자인',
   '보이드 오트밀',
   '원',
   '보이드 핑크베이지',
   '원',
   '품절',
   '보이드 그레이',
   '원',
   '품절',
   '보이드 네이비',
   '원',
   '보이드 딥그레이',
   '원',
   '품절',
   '보이드 베이지그레이',
   '원',
   '보이드 스노우',
   '원',
   '보이드 스카이블루',
   '원',
   '보이드 아쿠아마린',
   '원',
   '보이드 올리브그린',
   '원',
   '보이드 인디핑크',
   '원',
   '품절',
   '보이드 차콜',
   '원',
   '보이드 화이트',
   '원',
   '품절']],
 1: [['선택', '옐로우 ', '원', '연브라운 ', '원', '진브라운 ', '원', '네이비 ', '원']],
 2: [['사이즈', '배이불', '원', '홑이불', '원', '홑이불', '원']],
 3: [['색상',
   '요거트',
   '원',
   '바닐라',
   '원',
   '스트로베리',
   '원',
   '인절미',
   '원',
   '블루진',
   '원',
   '흑임자',
   '원']],
 5: [['옵션',
   '시트 고정밴드',
   '개입',
   '원',
   '시트 고정밴드',
   '개입',
   '원',
   '시트 고정밴드',
   '개입',
   '원',
   '시트 고정밴드',
   '개입',
   '원']],
 6: [['옵션', '원', '원', '원', '원', '원']],
 7: [['사이즈', '베개세트', '원', '베개세트', '원']],
 8: [['사이즈 및', '구성', '원', '원', '원']],
 9: [['사이즈', '슈퍼싱글', '원', '퀸', '원', '킹', '원']],
 10: [['선택',
   '구스이불 ',
   '솔리드 이불커버',
   '화이트 ',
   '원',
   '구스이불 ',
   '솔리드 이불커버',
   '베이지 '

In [63]:
df6 = DataFrame(dict6)
color_df = df6.T
color_df = color_df.rename(columns={0:'color'})
color_df

color
0    [디자인, 보이드 오트밀, 원, 보이드 핑크베이지, 원, 품절, 보이드 그레이, 원...
1           [선택, 옐로우 , 원, 연브라운 , 원, 진브라운 , 원, 네이비 , 원]
2                        [사이즈, 배이불, 원, 홑이불, 원, 홑이불, 원]
3    [색상, 요거트, 원, 바닐라, 원, 스트로베리, 원, 인절미, 원, 블루진, 원,...
5    [옵션, 시트 고정밴드, 개입, 원, 시트 고정밴드, 개입, 원, 시트 고정밴드, ...
..                                                 ...
495                              [컬러, 화이트, 원, 아이보리, 원]
496  [색상, 핑크 중형, 원, 핑크 대형, 원, 품절, 핑크 특대형, 원, 그레이 중형...
497  [색상, 원톤, 그레이, 원, 원톤, 핑크, 원, 원톤, 퍼플그레이, 원, 원톤, ...
498  [색상, 알러지케어 오트밀, 원, 알러지케어 퓨어화이트, 원, 알러지케어 베이비핑크...
499                             [종류, 차렵이불, 원, 차렵이불, 원]

[438 rows x 1 columns]

In [64]:
color_df.to_csv('오늘의집_색상.csv')

In [71]:
df =  pd.read_csv('오늘의집_최종전.csv')
df

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  \
0             0             0               0   
1             1             1               1   
2             2             2               2   
3             3             3               3   
4             4             4               4   
..          ...           ...             ...   
479         479           492             495   
480         480           493             496   
481         481           494             497   
482         482           495             498   
483         483           496             499   

                                              title   price  rating  \
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900     4.7   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900     5.0   
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900     4.7   
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900     4.9   
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종     NaN     NaN   
..                                              ...     ...     ...   
479                     클라우드 60수광목 차렵이불(세트) 2colors  49,900     4.6   
480          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500     4.5   
481     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400     4.9   
482       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900     4.7   
483                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900     4.8   

    review_num                                            comment  \
0          275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1           13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2          425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3           16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4          NaN                                                NaN   
..         ...                                                ...   
479      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  
0                    40수 트윌면(Cotton 100%)  
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷  
2                                 상세페이지참고  
3                                 상세페이지참조  
4                                     NaN  
..                                    ...  
479       겉감: 폴리에스터 100%\n충전재: 폴리에스터 100%  
480                cotton 100% 60수 고밀도 워싱  
481                              상세페이지 참고  
482                               상세페이지참조  
483                               상세페이지참조  

[484 rows x 9 columns]

In [67]:
len(df['Unnamed: 0.1.1'])

484

In [74]:
dictt = pd.concat([df, color_df], axis=1)
dictt

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  \
0           0.0           0.0             0.0   
1           1.0           1.0             1.0   
2           2.0           2.0             2.0   
3           3.0           3.0             3.0   
4           4.0           4.0             4.0   
..          ...           ...             ...   
495         NaN           NaN             NaN   
496         NaN           NaN             NaN   
497         NaN           NaN             NaN   
498         NaN           NaN             NaN   
499         NaN           NaN             NaN   

                                              title   price  rating  \
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900     4.7   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900     5.0   
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900     4.7   
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900     4.9   
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종     NaN     NaN   
..                                              ...     ...     ...   
495                                             NaN     NaN     NaN   
496                                             NaN     NaN     NaN   
497                                             NaN     NaN     NaN   
498                                             NaN     NaN     NaN   
499                                             NaN     NaN     NaN   

    review_num                                         comment  \
0          275        택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1           13                       배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2          425                여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3           16  이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4          NaN                                             NaN   
..         ...                                             ...   
495        NaN                                             NaN   
496        NaN                                             NaN   
497        NaN                                             NaN   
498        NaN                                             NaN   
499        NaN                                             NaN   

                                 material  \
0                    40수 트윌면(Cotton 100%)   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷   
2                                 상세페이지참고   
3                                 상세페이지참조   
4                                     NaN   
..                                    ...   
495                                   NaN   
496                                   NaN   
497                                   NaN   
498                                   NaN   
499                                   NaN   

                                                 color  
0    [디자인, 보이드 오트밀, 원, 보이드 핑크베이지, 원, 품절, 보이드 그레이, 원...  
1           [선택, 옐로우 , 원, 연브라운 , 원, 진브라운 , 원, 네이비 , 원]  
2                        [사이즈, 배이불, 원, 홑이불, 원, 홑이불, 원]  
3    [색상, 요거트, 원, 바닐라, 원, 스트로베리, 원, 인절미, 원, 블루진, 원,...  
4                                                  NaN  
..                                                 ...  
495                              [컬러, 화이트, 원, 아이보리, 원]  
496  [색상, 핑크 중형, 원, 핑크 대형, 원, 품절, 핑크 특대형, 원, 그레이 중형...  
497  [색상, 원톤, 그레이, 원, 원톤, 핑크, 원, 원톤, 퍼플그레이, 원, 원톤, ...  
498  [색상, 알러지케어 오트밀, 원, 알러지케어 퓨어화이트, 원, 알러지케어 베이비핑크...  
499                             [종류, 차렵이불, 원, 차렵이불, 원]  

[499 rows x 10 columns]

In [ ]:
# 제목 nan값 'Unknown'으로 채우기
dictt = dictt['title'].fillna('Unknown')

In [ ]:
# 데이터프레임 title열값에 'Unknown'이 들어가는 문자열 검색
title_index = dictt[dictt.str.contains('Unknown')].index
# 제목없는 행 없애기
dictt = dictt.drop(title_index, axis=0)

In [75]:
dictt.to_csv('오늘의집_크롤링_최종버전.csv')

# 전처리

In [39]:
# 저장해둔 url 불러오기
df = pd.read_csv('오늘의집_크롤링_최종버전.csv')
df

Unnamed: 0  Unnamed: 0.1                                           title  \
0             0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트   
1             1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm   
2             2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors   
3             3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors   
4             4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종   
..          ...           ...                                             ...   
479         479           479                     클라우드 60수광목 차렵이불(세트) 2colors   
480         480           480          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   
481         481           481     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors   
482         482           482       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors   
483         483           483                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors   

      price  rating review_num  \
0    29,900     4.7        275   
1    18,900     5.0         13   
2    15,900     4.7        425   
3    19,900     4.9         16   
4       NaN     NaN        NaN   
..      ...     ...        ...   
479  49,900     4.6      2,804   
480   4,500     4.5         26   
481  38,400     4.9         34   
482  29,900     4.7         11   
483  29,900     4.8        452   

                                               comment  \
0             택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1                            배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2                     여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3       이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4                                                  NaN   
..                                                 ...   
479         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  \
0                    40수 트윌면(Cotton 100%)   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷   
2                                 상세페이지참고   
3                                 상세페이지참조   
4                                     NaN   
..                                    ...   
479       겉감: 폴리에스터 100%\n충전재: 폴리에스터 100%   
480                cotton 100% 60수 고밀도 워싱   
481                              상세페이지 참고   
482                               상세페이지참조   
483                               상세페이지참조   

                                                 color  
0    ['디자인', '보이드 오트밀', '원', '보이드 핑크베이지', '원', '품절'...  
1    ['선택', '옐로우 ', '원', '연브라운 ', '원', '진브라운 ', '원'...  
2          ['사이즈', '배이불', '원', '홑이불', '원', '홑이불', '원']  
3    ['색상', '요거트', '원', '바닐라', '원', '스트로베리', '원', '...  
4                                                  NaN  
..                                                 ...  
479                                  ['사이즈', '원', '원']  
480  ['색상', '밀크화이트', '원', '크림베이지', '원', '내츄럴그레이', '...  
481  ['컬러선택', '프릴 퓨어', '화이트', '원', '프릴 크림', '바닐라', ...  
482  ['색상 및', '사이즈', '아이보리', '원', '아이보리', '원', '아이보...  
483  ['색상', '베이지', '원', '브라운', '원', '머스타드', '원', '그...  

[484 rows x 9 columns]

In [40]:
# 필요없는 열 삭제
df = df.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1)
df = df.fillna(0)
df

title   price  rating  \
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900     4.7   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900     5.0   
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900     4.7   
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900     4.9   
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종       0     0.0   
..                                              ...     ...     ...   
479                     클라우드 60수광목 차렵이불(세트) 2colors  49,900     4.6   
480          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500     4.5   
481     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400     4.9   
482       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900     4.7   
483                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900     4.8   

    review_num                                            comment  \
0          275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1           13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2          425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3           16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4            0                                                  0   
..         ...                                                ...   
479      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  \
0                    40수 트윌면(Cotton 100%)   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷   
2                                 상세페이지참고   
3                                 상세페이지참조   
4                                       0   
..                                    ...   
479       겉감: 폴리에스터 100%\n충전재: 폴리에스터 100%   
480                cotton 100% 60수 고밀도 워싱   
481                              상세페이지 참고   
482                               상세페이지참조   
483                               상세페이지참조   

                                                 color  
0    ['디자인', '보이드 오트밀', '원', '보이드 핑크베이지', '원', '품절'...  
1    ['선택', '옐로우 ', '원', '연브라운 ', '원', '진브라운 ', '원'...  
2          ['사이즈', '배이불', '원', '홑이불', '원', '홑이불', '원']  
3    ['색상', '요거트', '원', '바닐라', '원', '스트로베리', '원', '...  
4                                                    0  
..                                                 ...  
479                                  ['사이즈', '원', '원']  
480  ['색상', '밀크화이트', '원', '크림베이지', '원', '내츄럴그레이', '...  
481  ['컬러선택', '프릴 퓨어', '화이트', '원', '프릴 크림', '바닐라', ...  
482  ['색상 및', '사이즈', '아이보리', '원', '아이보리', '원', '아이보...  
483  ['색상', '베이지', '원', '브라운', '원', '머스타드', '원', '그...  

[484 rows x 7 columns]

In [41]:
#소재 nan값 없음으로 채우기
material_index = df[df['material'].str.contains('상세', na=True)].index
df.at[material_index ,'material'] = '없음'

In [42]:
# 색상이 아닌 다른 내용이 크롤링된 인덱스 찾아서 없음으로 바꾸기 
nocolor1 = df[df['color'].str.contains('사이즈', na=True)].index
nocolor2 = df[df['color'].str.contains('옵션', na=False)].index
nocolor3 = df[df['color'].str.contains('구스이불', na=False)].index
nocolor4 = df[df['color'].str.contains('차렵이불', na=False)].index
nocolor5 = df[df['color'].str.contains('추가상품', na=False)].index
nocolor6 = df[df['color'].str.contains('제품선택', na=False)].index
nocolor7 = df[df['color'].str.contains('구성', na=False)].index
nocolor8 = df[df['color'].str.contains('사각사각 알러지케어', na=False)].index
nocolor9 = df[df['color'].str.contains('소형', na=False)].index
nocolor10 = df[df['color'].str.contains('멀티싱글', na=False)].index
nocolor11 = df[df['color'].str.contains('베개커버', na=False)].index
nocolor12 = df[df['color'].str.contains('필수옵션', na=False)].index
nocolor13 = df[df['color'].str.contains('종류', na=False)].index

In [43]:
df.at[nocolor1 ,'color'] = '없음' 
df.at[nocolor2 ,'color'] = '없음' 
df.at[nocolor3 ,'color'] = '없음' 
df.at[nocolor4 ,'color'] = '없음' 
df.at[nocolor5 ,'color'] = '없음' 
df.at[nocolor6 ,'color'] = '없음' 
df.at[nocolor7 ,'color'] = '없음' 
df.at[nocolor8 ,'color'] = '없음' 
df.at[nocolor9 ,'color'] = '없음' 
df.at[nocolor10 ,'color'] = '없음' 
df.at[nocolor11 ,'color'] = '없음' 
df.at[nocolor12 ,'color'] = '없음' 
df.at[nocolor13 ,'color'] = '없음' 

In [ ]:
df.to_csv('오늘의집_크롤링_최종버전2.csv')

In [59]:
df = pd.read_csv('오늘의집_크롤링_최종버전2.csv')

In [60]:
# 필요없는 문자열 없애기
df['color'] = df['color'].str.replace('디자인','')
df['color'] = df['color'].str.replace('선택','')
df['color'] = df['color'].str.replace('원','')
df['color'] = df['color'].str.replace('품절','')
df['color'] = df['color'].str.replace('컬러','')
df['color'] = df['color'].str.replace('종류','')
df['color'] = df['color'].str.replace('차렵이불','')
df['color'] = df['color'].str.replace('색상','')

In [61]:
# 정규표현식 사용
import re
color_dict ={}

for i in range(484):
    d=df['color'][i]
    regex ='[가-힣]+'
    d=re.findall(regex,str(d))
    color_dict[i] = d
    
color_dict

{0: ['보이드',
  '오트밀',
  '보이드',
  '핑크베이지',
  '보이드',
  '그레이',
  '보이드',
  '네이비',
  '보이드',
  '딥그레이',
  '보이드',
  '베이지그레이',
  '보이드',
  '스노우',
  '보이드',
  '스카이블루',
  '보이드',
  '아쿠아마린',
  '보이드',
  '올리브그린',
  '보이드',
  '인디핑크',
  '보이드',
  '차콜',
  '보이드',
  '화이트'],
 1: ['옐로우', '연브라운', '진브라운', '네이비'],
 2: ['없음'],
 3: ['요거트', '바닐라', '스트로베리', '인절미', '블루진', '흑임자'],
 4: ['없음'],
 5: ['없음'],
 6: ['없음'],
 7: ['없음'],
 8: ['없음'],
 9: ['없음'],
 10: ['없음'],
 11: ['그레이', '브라운'],
 12: ['아이보리', '옐로우', '차콜'],
 13: ['없음'],
 14: ['없음'],
 15: ['없음'],
 16: ['없음'],
 17: ['없음'],
 18: ['없음'],
 19: ['없음'],
 20: ['베이지', '라인', '차콜', '라인'],
 21: ['없음'],
 22: ['없음'],
 23: ['없음'],
 24: ['없음'],
 25: ['없음'],
 26: ['없음'],
 27: ['없음'],
 28: ['없음'],
 29: ['상품', '화이트', '옷장', '서랍옷장', '이불장', '그레이', '옷장', '서랍옷장', '이불장'],
 30: ['없음'],
 31: ['없음'],
 32: ['아이보리', '베이지', '라벤더'],
 33: ['없음'],
 34: ['없음'],
 35: ['블랙', '그린', '옐로우', '레드', '퍼플', '네이비'],
 36: ['없음'],
 37: ['없음'],
 38: ['없음'],
 39: ['오렌지', '핑크', '바이올렛'],
 40: ['화이트',
  '네추럴베이지',
  '베

In [62]:
color_dict.values()

dict_values([['보이드', '오트밀', '보이드', '핑크베이지', '보이드', '그레이', '보이드', '네이비', '보이드', '딥그레이', '보이드', '베이지그레이', '보이드', '스노우', '보이드', '스카이블루', '보이드', '아쿠아마린', '보이드', '올리브그린', '보이드', '인디핑크', '보이드', '차콜', '보이드', '화이트'], ['옐로우', '연브라운', '진브라운', '네이비'], ['없음'], ['요거트', '바닐라', '스트로베리', '인절미', '블루진', '흑임자'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['그레이', '브라운'], ['아이보리', '옐로우', '차콜'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['베이지', '라인', '차콜', '라인'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['없음'], ['상품', '화이트', '옷장', '서랍옷장', '이불장', '그레이', '옷장', '서랍옷장', '이불장'], ['없음'], ['없음'], ['아이보리', '베이지', '라벤더'], ['없음'], ['없음'], ['블랙', '그린', '옐로우', '레드', '퍼플', '네이비'], ['없음'], ['없음'], ['없음'], ['오렌지', '핑크', '바이올렛'], ['화이트', '네추럴베이지', '베이지', '머스타드', '핑크', '민트', '딥그린', '스카이블루', '퍼플', '그레이', '차콜', '카라멜브라운', '올리브그린'], ['화이트', '차콜', '그레이', '피치', '그레이', '브라운', '아이보리', '아이보리', '그레이'], ['없음'], ['없음'], ['스테이', '아이보리', '스테이', '크림', '스테이', '파우더핑크', '스테이', '민트', '스테이', '그레이'], ['

In [63]:
df['color_list'] = color_dict.values()

In [64]:
df = df.drop('color', axis=1)
df

Unnamed: 0                                           title   price  \
0             0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900   
1             1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900   
2             2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900   
3             3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900   
4             4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종       0   
..          ...                                             ...     ...   
479         479                     클라우드 60수광목 차렵이불(세트) 2colors  49,900   
480         480          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500   
481         481     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400   
482         482       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900   
483         483                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900   

     rating review_num                                            comment  \
0       4.7        275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1       5.0         13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2       4.7        425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3       4.9         16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4       0.0          0                                                  0   
..      ...        ...                                                ...   
479     4.6      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480     4.5         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481     4.9         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482     4.7         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483     4.8        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                                 material  \
0                    40수 트윌면(Cotton 100%)   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷   
2                                      없음   
3                                      없음   
4                                      없음   
..                                    ...   
479       겉감: 폴리에스터 100%\n충전재: 폴리에스터 100%   
480                cotton 100% 60수 고밀도 워싱   
481                                    없음   
482                                    없음   
483                                    없음   

                                            color_list  
0    [보이드, 오트밀, 보이드, 핑크베이지, 보이드, 그레이, 보이드, 네이비, 보이드...  
1                               [옐로우, 연브라운, 진브라운, 네이비]  
2                                                 [없음]  
3                     [요거트, 바닐라, 스트로베리, 인절미, 블루진, 흑임자]  
4                                                 [없음]  
..                                                 ...  
479                                               [없음]  
480  [밀크화이트, 크림베이지, 내츄럴그레이, 앨리스핑크, 터키쉬제이드, 위트네이비, 샌...  
481  [프릴, 퓨어, 화이트, 프릴, 크림, 바닐라, 프릴, 데이지, 옐로우, 프릴, 머...  
482                                               [없음]  
483               [베이지, 브라운, 머스타드, 그레이, 화이트, 브릭레드, 그린]  

[484 rows x 8 columns]

In [65]:
#저장
df.to_csv('오늘의집_크롤링_최종버전3.csv')
df = pd.read_csv('오늘의집_크롤링_최종버전3.csv')

In [66]:
df = df.drop('Unnamed: 0', axis=1)

In [67]:
df['material'] = df['material'].str.replace('스테인리스 빨래집게','없음')
df['material'] = df['material'].str.replace('[겉감]','')
df['material'] = df['material'].str.replace('[커버]','')
df['material'] = df['material'].str.replace('[충천재]','')
df['material'] = df['material'].str.replace('원단:','')
df['material'] = df['material'].str.replace('충전재:','')
df['material'] = df['material'].str.replace('+',' ')
df['material'] = df['material'].str.replace('이노센트 이불봉 특대형 빨래건조대 7단','없음')
df['material'] = df['material'].str.replace('MY SPACE 항균압축팩','없음')
df['material'] = df['material'].str.replace('모던장롱 2400 세트 (옷장+서랍옷장+이불옷장)','없음')
df['material'] = df['material'].str.replace('앞:','')
df['material'] = df['material'].str.replace('뒤:','')
df['material'] = df['material'].str.replace('겉면:','')
df['material'] = df['material'].str.replace('매직이불압축팩 대형(밸브형) 85cmX100cm 4매','없음')
df['material'] = df['material'].str.replace('같감 -','')
df['material'] = df['material'].str.replace('안감 -','')
df['material'] = df['material'].str.replace('패드 -','')
df['material'] = df['material'].str.replace('충전재 -','')
df['material'] = df['material'].str.replace('매직이불압축팩 대형(밸브형) 85cmX100cm 4매','없음')
df['material'] = df['material'].str.replace('이불커버:','')
df['material'] = df['material'].str.replace('앞_','')
df['material'] = df['material'].str.replace('뒤_','')
df['material'] = df['material'].str.replace('앞/','')
df['material'] = df['material'].str.replace('뒤/','')
df['material'] = df['material'].str.replace('차렵이불,베개커버 겉감 / 패드앞지 :','')
df['material'] = df['material'].str.replace('이불/베개/패드 누빔충전재 : ','')
df['material'] = df['material'].str.replace('패드 뒷지 : ','')
df['material'] = df['material'].str.replace('앞면:','')
df['material'] = df['material'].str.replace('뒷면:','')
df['material'] = df['material'].str.replace('압축팩 4매 Set','')
df['material'] = df['material'].str.replace('베개커버 - ','')
df['material'] = df['material'].str.replace('이불 - ','')
df['material'] = df['material'].str.replace('침대패드및 매트리스커버 -','')
df['material'] = df['material'].str.replace('베개 솜 - ','')
df['material'] = df['material'].str.replace('차렵이불-솔리드:','')
df['material'] = df['material'].str.replace('베개커버-솔리드:',',')
df['material'] = df['material'].str.replace('프랑코 이불 압축팩 1P','없음')
df['material'] = df['material'].str.replace('따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷','없음')

In [68]:
notitle_index1 = df[df['title'].str.contains('집게')].index
notitle_index2 = df[df['title'].str.contains('침대스커트')].index
notitle_index3 = df[df['title'].str.contains('빨래건조대')].index
notitle_index4 = df[df['title'].str.contains('압축팩')].index
notitle_index5 = df[df['title'].str.contains('정리함')].index

In [69]:
llist =[27, 47, 82, 94, 187, 205, 311, 340, 356, 437, 16,  56,  80,  93, 117, 129, 143, 169, 197, 204, 213, 230, 233,246, 249, 257, 281, 299, 340, 345, 358, 366, 367, 389, 397, 440,471]
df =df.drop(notitle_index1, axis=0)
df =df.drop(notitle_index2, axis=0)
df =df.drop(notitle_index3, axis=0)
df =df.drop(llist, axis=0)

In [70]:
df

Unnamed: 0.1                                           title   price  \
0               0               [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29,900   
1               1  따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18,900   
2               2           멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15,900   
3               3            데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19,900   
4               4          마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종       0   
..            ...                                             ...     ...   
479           479                     클라우드 60수광목 차렵이불(세트) 2colors  49,900   
480           480          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4,500   
481           481     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38,400   
482           482       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29,900   
483           483                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29,900   

     rating review_num                                            comment  \
0       4.7        275           택배 받아서 세탁기 돌렸는데… 이렇게 됐네요. 세탁기 언제 청소 하죠….   
1       5.0         13                          배송도 빠르고 너무 예뻐요 다른것도 사고싶어요   
2       4.7        425                   여름이불로 구매했는데 겨울엔 패드위에 깔아놓고 쓰고있어요.   
3       4.9         16     이불 진짜.. 너무 부드럽고 완전 예뻐요ㅠㅠ 진짜 이불 잘산 것 같아요 최고입니당♥   
4       0.0          0                                                  0   
..      ...        ...                                                ...   
479     4.6      2,804         지금 반년째 사용중입니다 ㅎㅎ 너무너무 마음에 들어요 엄청 고민하고 고른건데   
480     4.5         26  일단 디자인 자체가 깔끔해서 놓아두기 좋고요 용량도 커서 안쓰는 이불이랑 베개 들어...   
481     4.9         34  색감 자체는 굉장히 맘에 들어요 ! 두께감이 있는 편은 아닙니다 대신 4계절용으로 ...   
482     4.7         11  조명때문에 색이 잘 나오지는 않았지만 만족하면서 잘 쓰고있어요 제가 원하는 부들부들...   
483     4.8        452  풍성하면서도 가벼워서 사계절 내내 덮을 수 았을 것 같아요 깔끔한 화이트 컬러에 누...   

                        material  \
0           40수 트윌면(Cotton 100%)   
1                             없음   
2                             없음   
3                             없음   
4                             없음   
..                           ...   
479  : 폴리에스터 100%\n전: 폴리에스터 100%   
480       cotton 100% 60수 고밀도 워싱   
481                           없음   
482                           없음   
483                           없음   

                                            color_list  
0    ['보이드', '오트밀', '보이드', '핑크베이지', '보이드', '그레이', '...  
1                       ['옐로우', '연브라운', '진브라운', '네이비']  
2                                               ['없음']  
3         ['요거트', '바닐라', '스트로베리', '인절미', '블루진', '흑임자']  
4                                               ['없음']  
..                                                 ...  
479                                             ['없음']  
480  ['밀크화이트', '크림베이지', '내츄럴그레이', '앨리스핑크', '터키쉬제이드'...  
481  ['프릴', '퓨어', '화이트', '프릴', '크림', '바닐라', '프릴', '...  
482                                             ['없음']  
483  ['베이지', '브라운', '머스타드', '그레이', '화이트', '브릭레드', '...  

[428 rows x 8 columns]

In [71]:
df['price'] = df['price'].str.replace(',','')
df['price']

0      29900
1      18900
2      15900
3      19900
4          0
       ...  
479    49900
480     4500
481    38400
482    29900
483    29900
Name: price, Length: 428, dtype: object

In [72]:
def black(x):
    if x in range(50000) :        
        return '저가'
    elif x in range(50000,100000) :
        return '중가'
    else:
        return '고가'
    
df['Range'] = df['price'].apply(lambda x: black(x))

In [73]:
df.to_csv('오늘의집_크롤링_최종.csv')
df = pd.read_csv('오늘의집_크롤링_최종.csv')

In [74]:
# 정규표현식 사용
import re
material_dict ={}

for i in range(428):
    m=df['material'][i]
    regex ='[가-힣]+'
    m=re.findall(regex,str(m))
    material_dict[i] = m
    
material_dict

{0: ['수', '트윌면'],
 1: ['없음'],
 2: ['없음'],
 3: ['없음'],
 4: ['없음'],
 5: ['없음'],
 6: ['초광폭', '수', '사틴면', '고밀도'],
 7: ['수', '면', '전', '구스솜털', '구스오라기털', '구스페더', '수', '사틴면', '고밀도', '초광폭'],
 8: ['없음'],
 9: ['없음'],
 10: ['면'],
 11: ['없음'],
 12: ['폴리에스터'],
 13: ['고밀도', '마이크로화이바', '휴비스', '폴라필', '옥수수솜', '전'],
 14: ['기능성', '폴리'],
 15: ['없음'],
 16: ['오가닉', '순면', '수', '전', '옥수수식물성추출', '폴리에스테르'],
 17: ['없음'],
 18: ['없음'],
 19: ['없음'],
 20: ['폴리에스테르', '전', '마이크로화이바'],
 21: ['없음'],
 22: ['폴라폴리스'],
 23: ['모던장롱', '세트', '옷장', '서랍옷장', '이불옷장'],
 24: ['없음'],
 25: ['없음'],
 26: ['없음'],
 27: ['공통',
  '워싱',
  '폴리에스터',
  '전',
  '차렵이불',
  '토퍼',
  '폴리에스터',
  '밑면',
  '토퍼',
  '폴리에스터',
  '논슬립가공'],
 28: ['수', '트윌', '면'],
 29: ['없음'],
 30: ['없음'],
 31: ['면',
  '원단에',
  '테두리',
  '두줄',
  '실',
  '포인트를',
  '넣어',
  '세련되고',
  '깔끔한',
  '호텔식디자인의',
  '이불'],
 32: ['폴리에스터', '전', '폴리에스터'],
 33: ['세미', '나노화이바', '폴리에스테르', '마이크로화이바', '극세사'],
 34: ['홑이불', '베개마이크로', '모달', '면', '베개', '순면', '수'],
 35: ['면', '순면', '수', '다운프루프', '가공', '전', 

In [75]:
df['material'] = material_dict.values()
df.to_csv('오늘의집_크롤링_최종.csv')

# CBF_추천

In [79]:
df = pd.read_csv('오늘의집_크롤링_최종.csv')
df = df.drop(['Unnamed: 0','Unnamed: 0.1', 'Unnamed: 0.1.1', 'comment'], axis=1)
df

title  price  rating review_num  \
0                 [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트  29900     4.7        275   
1    따뜻한 극세사 소프트 터치 겨울 무릎 담요 이불 소파 대형 블랭킷 150x200cm  18900     5.0         13   
2             멜로우 코튼 모달 피그먼트 와플 홑이불 (B/S/Q) 5colors  15900     4.7        425   
3              데일리 진드기방지 먼지없는 차렵이불 (SS/Q/K) 6colors  19900     4.9         16   
4            마틸라 시즌 베스트 극세사 차렵이불/이불커버/패드 원데이 특가 34종      0     0.0          0   
..                                              ...    ...     ...        ...   
423                     클라우드 60수광목 차렵이불(세트) 2colors  49900     4.6      2,804   
424          대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color   4500     4.5         26   
425     [5%쿠폰] 피치스킨 그리드 원톤/투톤 봄차렵이불세트(SS/Q) 9colors  38400     4.9         34   
426       반려동물 털&먼지 걱정끝 알러지케어 차렵이불세트 (SS/Q) 7colors  29900     4.7         11   
427                     블랑슈 세미워싱 차렵이불 (S/Q) 2colors  29900     4.8        452   

                    material  \
0               ['수', '트윌면']   
1                     ['없음']   
2                     ['없음']   
3                     ['없음']   
4                     ['없음']   
..                       ...   
423  ['폴리에스터', '전', '폴리에스터']   
424       ['수', '고밀도', '워싱']   
425                   ['없음']   
426                   ['없음']   
427                   ['없음']   

                                            color_list Range  
0    ['보이드', '오트밀', '보이드', '핑크베이지', '보이드', '그레이', '...    고가  
1                       ['옐로우', '연브라운', '진브라운', '네이비']    고가  
2                                               ['없음']    고가  
3         ['요거트', '바닐라', '스트로베리', '인절미', '블루진', '흑임자']    고가  
4                                               ['없음']    고가  
..                                                 ...   ...  
423                                             ['없음']    고가  
424  ['밀크화이트', '크림베이지', '내츄럴그레이', '앨리스핑크', '터키쉬제이드'...    고가  
425  ['프릴', '퓨어', '화이트', '프릴', '크림', '바닐라', '프릴', '...    고가  
426                                             ['없음']    고가  
427  ['베이지', '브라운', '머스타드', '그레이', '화이트', '브릭레드', '...    고가  

[428 rows x 7 columns]

In [80]:
#문자열로 된 리스트를 그냥 리스트 형태로 바꿔주기
import ast
from ast import literal_eval 
df['color_list'] = df['color_list'].apply(literal_eval)
df['material'] = df['material'].apply(literal_eval)

## 색상유사도

In [82]:
df['color_list_literal'] = df['color_list'].apply(lambda x : (' ').join(x))
df['color_list_literal']

0      보이드 오트밀 보이드 핑크베이지 보이드 그레이 보이드 네이비 보이드 딥그레이 보이드...
1                                      옐로우 연브라운 진브라운 네이비
2                                                     없음
3                              요거트 바닐라 스트로베리 인절미 블루진 흑임자
4                                                     없음
                             ...                        
423                                                   없음
424     밀크화이트 크림베이지 내츄럴그레이 앨리스핑크 터키쉬제이드 위트네이비 샌드그레이 무드차콜
425             프릴 퓨어 화이트 프릴 크림 바닐라 프릴 데이지 옐로우 프릴 머스크 멜론
426                                                   없음
427                         베이지 브라운 머스타드 그레이 화이트 브릭레드 그린
Name: color_list_literal, Length: 428, dtype: object

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
# CountVectorizer로 학습시켜 428개 상품명에 대한 1541개 색상의 '색상 매트릭스' 생성
# 상품명 별 색상 인덱스 사전을 만들어준다
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2)) 
color_mat = count_vect.fit_transform(df['color_list_literal'])
print(color_mat.shape)
print(color_mat)

(428, 1541)
  (0, 595)	13
  (0, 1009)	1
  (0, 1445)	1
  (0, 30)	1
  (0, 114)	1
  (0, 214)	1
  (0, 592)	1
  (0, 798)	1
  (0, 814)	1
  (0, 908)	1
  (0, 1027)	1
  (0, 1102)	1
  (0, 1141)	1
  (0, 1494)	1
  (0, 603)	1
  (0, 1014)	1
  (0, 607)	1
  (0, 1448)	1
  (0, 596)	1
  (0, 45)	1
  (0, 597)	1
  (0, 119)	1
  (0, 598)	1
  (0, 216)	1
  (0, 599)	1
  :	:
  (425, 1385)	1
  (425, 1351)	1
  (425, 1524)	1
  (425, 1384)	1
  (425, 1218)	1
  (425, 503)	1
  (425, 1378)	1
  (425, 192)	1
  (425, 991)	1
  (425, 1380)	1
  (425, 375)	1
  (426, 954)	1
  (427, 30)	1
  (427, 1494)	1
  (427, 618)	1
  (427, 560)	1
  (427, 71)	1
  (427, 379)	1
  (427, 64)	1
  (427, 639)	1
  (427, 621)	1
  (427, 574)	1
  (427, 380)	1
  (427, 1509)	1
  (427, 641)	1


In [86]:
# CountVectorizer로 학습시켜 428개 상품명에 대한 487개 색상의 '색상 매트릭스' 생성
count_vect2 = CountVectorizer(min_df=1, ngram_range=(1, 1))  # min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
color_mat2 = count_vect2.fit_transform(df['color_list_literal'])
print(color_mat2.shape)
print(color_mat2)

(428, 487)
  (0, 181)	13
  (0, 308)	1
  (0, 463)	1
  (0, 10)	1
  (0, 30)	1
  (0, 49)	1
  (0, 179)	1
  (0, 241)	1
  (0, 248)	1
  (0, 271)	1
  (0, 311)	1
  (0, 342)	1
  (0, 358)	1
  (0, 479)	1
  (1, 30)	1
  (1, 300)	1
  (1, 297)	1
  (1, 356)	1
  (2, 290)	1
  (3, 319)	1
  (3, 156)	1
  (3, 253)	1
  (3, 343)	1
  (3, 204)	1
  (3, 485)	1
  :	:
  (424, 387)	1
  (424, 152)	1
  (424, 29)	1
  (424, 286)	1
  (424, 400)	1
  (424, 328)	1
  (424, 221)	1
  (424, 136)	1
  (425, 479)	1
  (425, 300)	1
  (425, 156)	1
  (425, 382)	1
  (425, 444)	4
  (425, 432)	1
  (425, 42)	1
  (425, 113)	1
  (425, 122)	1
  (426, 290)	1
  (427, 10)	1
  (427, 479)	1
  (427, 186)	1
  (427, 178)	1
  (427, 14)	1
  (427, 115)	1
  (427, 190)	1


In [87]:
# 코사인 유사도에 의해 487개 이불 각각 유사한 이불들이 계산됨
from sklearn.metrics.pairwise import cosine_similarity
color_sim = cosine_similarity(color_mat, color_mat)

print(color_sim.shape)
print(color_sim[:10])

(428, 428)
[[1.         0.02627035 0.         ... 0.01174846 0.         0.03855433]
 [0.02627035 1.         0.         ... 0.06388766 0.         0.        ]
 [0.         0.         1.         ... 0.         1.         0.        ]
 ...
 [0.         0.         1.         ... 0.         1.         0.        ]
 [0.04012862 0.         0.         ... 0.         0.         0.32025631]
 [0.03108349 0.16903085 0.         ... 0.07559289 0.         0.        ]]


In [88]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
# 유사도가 높은 이불을 앞에서부터 순서대로 보여줌
color_sim_sorted_ind = color_sim.argsort()[:, ::-1]
print(color_sim_sorted_ind) 

[[  0  47 154 ... 233 234 213]
 [  1  29 301 ... 282 283 213]
 [123  58 305 ... 253 254   0]
 ...
 [425 385 180 ... 227 228 213]
 [123  58 305 ... 253 254   0]
 [427 235 225 ... 340 204 213]]


## 소재 유사도

In [89]:
df['material'] = df['material'].apply(lambda x : (' ').join(x))
df['material']

0              수 트윌면
1                 없음
2                 없음
3                 없음
4                 없음
           ...      
423    폴리에스터 전 폴리에스터
424         수 고밀도 워싱
425               없음
426               없음
427               없음
Name: material, Length: 428, dtype: object

In [90]:
m_index = df[df['material'].str.contains('없음', na=True)].index
m_index

Int64Index([  1,   2,   3,   4,   5,   8,   9,  11,  15,  17,
            ...
            399, 405, 407, 413, 416, 418, 420, 425, 426, 427],
           dtype='int64', length=168)

In [91]:
df2 = df.drop(m_index, axis=0)
df2

title   price  rating review_num  \
0           [단독] 보이드 13COLOR 순면 호텔식 이불커버 침구세트   29900     4.7        275   
6       (60수면100%)특급호텔 납품 솔리드 이불커버 SS/Q/K 6컬러   44000     4.8         82   
7       (한파용/세트)특급호텔 납품 구스충전재100% 이불+솔리드 이불커버  109000     4.7        507   
10   모네 100수 고밀도 피그먼트 이불커버세트 (S/QK겸용) 4colors  109000     4.7         21   
12                   구스이불처럼 포근한 워셔블 이불솜 3size   99000     4.7        301   
..                                        ...     ...     ...        ...   
419              앨리스 프리미엄 순면 이불커버세트 SS/Q/K/EK   31900     4.8         16   
421     데일리 고밀도 코튼 호텔침구커버SET(이불+베개커버) 11color   88000     4.6        638   
422         샌디 마이크로모달 사계절 차렵이불세트 SS/Q 3colors   35900     4.7         33   
423               클라우드 60수광목 차렵이불(세트) 2colors   49900     4.6      2,804   
424    대용량 패브릭 리빙박스 의류보관 이불보관 언더배드 파우치 3color    4500     4.5         26   

                                 material  \
0                                   수 트윌면   
6                           초광폭 수 사틴면 고밀도   
7    수 면 전 구스솜털 구스오라기털 구스페더 수 사틴면 고밀도 초광폭   
10                                      면   
12                                  폴리에스터   
..                                    ...   
419             면 고밀도 가공 수 전 헝가리산 거위솜털 깃털   
421                                    순면   
422                     세미화이바 피치 스킨 폴리에스터   
423                         폴리에스터 전 폴리에스터   
424                              수 고밀도 워싱   

                                            color_list Range  \
0    [보이드, 오트밀, 보이드, 핑크베이지, 보이드, 그레이, 보이드, 네이비, 보이드...    고가   
6                                                 [없음]    고가   
7                                                 [없음]    고가   
10                                                [없음]    고가   
12                                                [없음]    고가   
..                                                 ...   ...   
419                            [화이트, 베이지, 핑크, 민트, 그레이]    고가   
421    [디저트, 코코베이지, 파스텔, 블루치즈, 파스텔, 크림라일락, 파스텔, 바나나크림]    고가   
422  [퓨어화이트, 바닐라크림, 버터, 파스텔라일락, 페어그린, 정글그린, 잉크블루, 모...    고가   
423                                               [없음]    고가   
424  [밀크화이트, 크림베이지, 내츄럴그레이, 앨리스핑크, 터키쉬제이드, 위트네이비, 샌...    고가   

                                    color_list_literal  
0    보이드 오트밀 보이드 핑크베이지 보이드 그레이 보이드 네이비 보이드 딥그레이 보이드...  
6                                                   없음  
7                                                   없음  
10                                                  없음  
12                                                  없음  
..                                                 ...  
419                                  화이트 베이지 핑크 민트 그레이  
421             디저트 코코베이지 파스텔 블루치즈 파스텔 크림라일락 파스텔 바나나크림  
422  퓨어화이트 바닐라크림 버터 파스텔라일락 페어그린 정글그린 잉크블루 모닝스카이 코발트...  
423                                                 없음  
424   밀크화이트 크림베이지 내츄럴그레이 앨리스핑크 터키쉬제이드 위트네이비 샌드그레이 무드차콜  

[260 rows x 8 columns]

In [92]:
# CountVectorizer로 학습시켜 259개 상품명에 대한 1000개 소재의 '소재 매트릭스' 생성
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2)) 
material_mat = count_vect.fit_transform(df2['material'])
print(material_mat.shape)
print(material_mat)

(260, 704)
  (0, 555)	1
  (1, 505)	1
  (1, 263)	1
  (1, 17)	1
  (1, 506)	1
  (1, 264)	1
  (2, 505)	1
  (2, 263)	1
  (2, 17)	1
  (2, 264)	1
  (2, 45)	1
  (2, 48)	1
  (2, 50)	1
  (2, 46)	1
  (2, 49)	1
  (2, 51)	1
  (2, 25)	1
  (4, 603)	1
  (5, 17)	1
  (5, 151)	1
  (5, 700)	1
  (5, 591)	1
  (5, 374)	1
  (5, 19)	1
  (5, 154)	1
  :	:
  (253, 659)	1
  (253, 400)	1
  (254, 151)	1
  (255, 17)	1
  (255, 0)	1
  (255, 64)	1
  (255, 678)	1
  (255, 7)	1
  (255, 18)	1
  (255, 3)	1
  (255, 679)	1
  (255, 8)	1
  (256, 306)	1
  (257, 603)	1
  (257, 283)	1
  (257, 664)	1
  (257, 318)	1
  (257, 285)	1
  (257, 665)	1
  (257, 319)	1
  (258, 603)	2
  (258, 630)	1
  (259, 17)	1
  (259, 394)	1
  (259, 23)	1


In [93]:
# CountVectorizer로 학습시켜 259개 상품명에 대한 401개 소재의 '소재 매트릭스' 생성
count_vect2 = CountVectorizer(min_df=1, ngram_range=(1, 1))  # min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
material_mat2 = count_vect2.fit_transform(df2['material'])
print(material_mat2.shape)
print(material_mat2)

(260, 288)
  (0, 239)	1
  (1, 215)	1
  (1, 110)	1
  (1, 8)	1
  (2, 215)	1
  (2, 110)	1
  (2, 8)	1
  (2, 17)	1
  (2, 18)	1
  (2, 19)	1
  (4, 257)	1
  (5, 8)	1
  (5, 62)	1
  (5, 287)	1
  (5, 254)	1
  (5, 159)	1
  (6, 22)	1
  (6, 256)	1
  (7, 155)	1
  (7, 132)	1
  (7, 160)	1
  (7, 258)	1
  (8, 62)	1
  (8, 258)	1
  (9, 253)	1
  :	:
  (251, 263)	1
  (251, 264)	1
  (252, 257)	6
  (252, 91)	1
  (252, 65)	1
  (252, 28)	3
  (252, 223)	1
  (253, 256)	1
  (253, 251)	1
  (253, 268)	1
  (253, 171)	1
  (254, 62)	1
  (255, 8)	1
  (255, 0)	1
  (255, 24)	1
  (255, 276)	1
  (255, 3)	1
  (256, 132)	1
  (257, 257)	1
  (257, 119)	1
  (257, 270)	1
  (257, 133)	1
  (258, 257)	2
  (259, 8)	1
  (259, 170)	1


In [94]:
from sklearn.metrics.pairwise import cosine_similarity
material_sim = cosine_similarity(material_mat, material_mat)

print(material_sim.shape)
print(material_sim[:10])

(260, 260)
[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.53935989 ... 0.         0.         0.25819889]
 [0.         0.53935989 1.         ... 0.         0.         0.17407766]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [95]:
material_sim_sorted_ind = material_sim.argsort()[:, ::-1] # ::-1 : 역순으로 정렬
print(material_sim_sorted_ind)

[[  0 106  32 ... 166 165 129]
 [  1   2  18 ... 148 147   0]
 [  2   1  95 ... 148 147   0]
 ...
 [234 257  91 ... 151 150   0]
 [ 73 175 160 ... 155 154   0]
 [259 122 103 ... 149 148   0]]


## 리뷰수 반영한 별점(가중평균)

In [96]:
df[['title','price', 'rating', 'review_num','material', 'color_list_literal','Range']].sort_values('rating', ascending=False)

title   price  rating  \
317  밍크촉감 프리미엄 10mm 에슐리 겨울 극세사 차렵이불 침구세트(3size/3col...  134800     5.0   
22                        큰 체크 항공담요/봄가을 야외행사용 휴대이불 사은품    4130     5.0   
236                                  1+1 블랑 캐리어형 의류보관함   39000     5.0   
243        겉바속촉 호텔식 고밀도 순면60수 사계절 이불커버(SS/Q&K)-13color   34900     5.0   
383       오가닉인증100 순면 친환경옥수수솜 오가닉라이프 차렵이불(세트) 체크3color   52500     5.0   
..                                                 ...     ...     ...   
240                         순수 유기농 오가닉 면100% 차렵이불세트 3종       0     0.0   
337                     패브릭 파우치형 이불 의류보관함 빨래바구니 3color    7800     0.0   
385                     [슈퍼세일] 1+1 갓성비 리빙박스 이불/옷정리용 모음       0     0.0   
46                   체크 플라워 에스닉 패턴 베개커버 이불커버 BEST ITEM       0     0.0   
48                   체크 플라워 패턴 디자인 이불커버 베개커버 BEST ITEM       0     0.0   

    review_num                   material  \
317          4  한샘 샘베딩 이불정리함 한샘 샘베딩 이불정리함   
22           1                      폴라폴리스   
236          2                      폴리에스터   
243         13              폴리에스터 전 폴리에스터   
383          7                          면   
..         ...                        ...   
240          0                         없음   
337          0                          전   
385          0               수 오가닉 면 멜란 면   
46           0                         없음   
48           0                         없음   

                            color_list_literal Range  
317                                         없음    고가  
22                                          없음    고가  
236  애플그린 오트밀 베이비블루 시나몬 핑크뮬리 라벤더 옐로우 버터 그레이 차콜    고가  
243                              루나 미스트 던 미드나잇    고가  
383                                         없음    고가  
..                                         ...   ...  
240                       베이지 옐로우 딸기우유핑크 민트 블랙    고가  
337                                         없음    고가  
385          프릴 라일락퍼플 프릴 모스그린 프릴 모카베이지 프릴 멜란챠콜    고가  
46                                          없음    고가  
48                                          없음    고가  

[428 rows x 7 columns]

In [97]:
df['review_num'] = df['review_num'].str.replace(',','')
df['review_num'] = pd.to_numeric(df['review_num'])
df2['review_num'] = df2['review_num'].str.replace(',','')
df2['review_num'] = pd.to_numeric(df2['review_num'])

In [98]:
# 상위 60%에 해당하는 리뷰수를 최소 리뷰수인 m으로 지정
C = df['rating'].mean()  # C :전체 상품에 대한 평균 평점
m = df['review_num'].quantile(0.6)
C = df2['rating'].mean() 
m = df2['review_num'].quantile(0.6)

In [99]:
def weighted_vote_average(record): #가중평점
    v = record['review_num']  #리뷰수
    R = record['rating'] #별점
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )

In [100]:
# 기존 데이터에 가중평점 칼럼 추가
df['weighted_rating'] = df.apply(weighted_vote_average, axis=1)
df2['weighted_rating'] = df2.apply(weighted_vote_average, axis=1)

In [101]:
# 가중평점(weighted_vote) 기준으로 상품 순위 뽑아보기
df[['title','price','weighted_rating', 'rating', 'review_num', 'material', 'color_list_literal','Range']].sort_values('weighted_rating', ascending=False)

title  price  weighted_rating  \
256         노스베어 프리미엄 10mm 극세사차렵이불 SS/Q/K/LK 시즌오프  59900         4.784522   
176  [단독] 시즌오프 1+1 극세사 밍크담요 9종 택1(소형/대형/특대형) 시즌오프   7900         4.777413   
230       [단독]컬러테리어 로이 밴드형 밴딩 침대패드 2size 12colors  15900         4.776141   
25     [5%쿠폰] 먼지없는 부드러운 깅엄체크 차렵이불세트 알러지케어 침구 시즌오프  31700         4.773557   
228               유기농 오가닉 순면 차렵이불 친환경 옥수수솜 3color  39900         4.772466   
..                                            ...    ...              ...   
332     호텔콜렉션 80수/100수 침구세트 모음전 (이불커버+베개커버) S/Q/K      0         4.159615   
143          아토피협회 추천 알러지케어 전문, 아토앤알로 차렵/베개솜 초특가전      0         4.159615   
320                     22년도 SS신상 이불세트 + 베스트셀러 모음      0         4.159615   
64                (베개커버증정)딜라잇 비비드 차박 캠핑이불 6colors  19900         4.159615   
134      데일리 진드기방지 먼지없는 차렵이불(세트) (SS/Q/K) 6colors  19900         4.126369   

     rating  review_num                                 material  \
256     4.8        4756                                       순면   
176     4.8        3222  앞 세미화이바 피치 스킨 폴리에스터 뒤 마이크로화이바 극세사 폴리에스터   
230     4.8        3044        원단 이불 앞면 뒷면 오가닉코튼 순면 수 전제 항균 옥수수솜   
25      4.8        2735                                       없음   
228     4.8        2622                              초극세사 마이크로화이   
..      ...         ...                                      ...   
332     0.0           0                            순면 수 피그먼트 워싱면   
143     0.0           0                              실크극세사 폴리에스터   
320     0.0           0                                      극세사   
64      0.0           0                                       없음   
134     3.8          12                     이노센트 이불봉 특대형 빨래건조대 단   

                                    color_list_literal Range  
256                           오트밀베이지 크림화이트 피치핑크 빈티지그레이    고가  
176  세미극세사 테디베어 세미극세사 젤리곰 세미극세사 소프트래빗 세미극세사 스위트피 세미...    고가  
230                                                 없음    고가  
25                                                  없음    고가  
228                                          블루 오렌지 차콜    고가  
..                                                 ...   ...  
332                                           아이보리 브라운    고가  
143                                       블랙 화이트 블루 핑크    고가  
320                           에슐리 그레이 에슐리 아이보리 에슐리 베이지    고가  
64                     그린블루 핑크민트 퍼플옐로우 옐로우핑크 민트그린 블루핑크    고가  
134                                                 없음    고가  

[428 rows x 8 columns]

## 색상 유사성 높은 순으로 뽑고 가중평점순으로 추천

In [102]:
# 면 100%인 차렵이불 DataFrame추출
title_goods = df[df['title'].str.contains('면100% 차렵이불')]

In [103]:
title_index = title_goods.index.values
title_index

array([240], dtype=int64)

In [104]:
color_sim_sorted_ind[title_index]

array([[240, 159, 115, 352, 296, 419, 334, 145,  29, 131, 377, 129, 299,
        278, 137,  65, 341,  90, 339,  26, 225, 361, 379, 251, 235, 326,
        263, 276, 414,   9, 416, 253,  56, 255,  34, 196, 362,   1,  45,
        404, 360, 143,  73, 304,  16, 151, 372, 373, 128,  81, 347, 427,
        349, 318, 346,  91, 320, 117, 163, 292, 208, 236, 402, 161, 364,
        395,  89, 425, 258, 124, 365, 390,  38, 136, 328, 323, 149,  68,
        141, 166, 410, 181, 127, 180, 126, 179, 130, 125, 157, 121, 182,
        116, 111, 112, 113, 114, 187, 186, 185, 183, 118, 119, 184, 120,
        122, 123, 178, 174, 132, 164, 146, 147, 109, 148, 150, 165, 162,
        168, 152, 153, 154, 155, 156, 160, 167, 169, 177, 173, 133, 176,
        175, 134, 158, 135, 138, 144, 172, 139, 171, 140, 170, 142, 110,
         87, 108,  40,  28,  30,  31,  32,  33,  35,  36,  37,  39,  41,
         53,  42,  43,  44,  46,  47,  48,  49,  50,  51,  27,  25,  24,
         23,   2,   3,   4,   5,   6,   7,   8,  10

In [105]:
similar_indexes = color_sim_sorted_ind[title_index, :30]
similar_indexes

array([[240, 159, 115, 352, 296, 419, 334, 145,  29, 131, 377, 129, 299,
        278, 137,  65, 341,  90, 339,  26, 225, 361, 379, 251, 235, 326,
        263, 276, 414,   9]], dtype=int64)

In [106]:
# 추출된 top_30 index들 출력. top_30 index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경하고싶어서 (-1)을 함
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[240 159 115 352 296 419 334 145  29 131 377 129 299 278 137  65 341  90
 339  26 225 361 379 251 235 326 263 276 414   9]


In [107]:
similar_indexes = similar_indexes[similar_indexes != title_index]
df.iloc[similar_indexes].sort_values('weighted_rating', ascending=False)[:15]

title   price  rating  review_num  \
377   [오늘의딜/10%쿠폰]면의 캐시미어 고밀도100수 수피마코튼 프리미엄 침구세트   89700     4.8        1253   
339        최고급 코마사 도즈 60수 고밀도순면 이불커버(세트) 10colors   41900     4.7        2376   
137  고밀도 10mm 라셀극세사 알러지케어 차렵이불세트 S/SS/Q/K 2colors   55700     4.9         228   
131              모노디 밍크 극세사 차렵이불세트 6colors (컬러추가)   34900     4.7         741   
263              헤링본 니쉬 보아밍크 극세사 차렵이불 풀세트 SS/Q/LK   57900     4.8         290   
159              기절 포그니 풀세트(이불+토퍼+릴렉스필로우) SS/Q/SK   65900     4.6        1304   
235                             파우치형 옷장 정리 이불 보관함    4800     4.6         429   
361       클린 순면 고밀도 60수 양면 이불커버 단품 (SS/Q) 3colors   29000     4.6         321   
278  [오늘의딜/5%쿠폰] 에브리데이 코튼 이불커버세트 25colors / 4size  118400     4.5         730   
115    피그먼트 워싱 이불겸 패드 아사60수(면100%) 3type 26colors   10700     4.8          99   
26               빈티지 레이스 린넨 광목 원형2, 4,6인용 미니 테이블보   12900     4.8          84   
379               에어프레시 먼지없는 이불커버(단품) 솔리드 5colors   24900     4.7         103   
9                (당일발송) 따뜻한 1인용 수술블랭킷 쇼파 침대 무릎 담요   29800     4.7          88   
352            인디체크 순면 이불커버세트 (SS/Q/K/EK) 3colors   24900     4.7          72   
225               테라조마블 4color 자체제작 사계절이불세트 3size  115000     4.6          98   

                                material                           color_list  \
377                            침대시트 고정집게       [옐로우, 애쉬민트, 화이트, 베이지, 그레이, 차콜]   
339         울트라파인화이바 폴리에스터 전 고급이불솜 폴리에스터                        [베이지, 카멜, 차콜]   
137                마이크로 모달 면 마이크로화이바 극세사  [크림화이트, 베이지, 머스타드, 핑크, 민트, 딥그린, 차콜]   
131                                   없음       [옐로우, 애쉬민트, 화이트, 베이지, 그레이, 차콜]   
263                    피그먼트워싱면 면 전 폴리에스터                    [아이보리, 베이지, 연그레이]   
159                                   없음           [베이지, 옐로우, 딸기우유핑크, 민트, 블랙]   
235                        순면 수 피그먼트 워싱면                      [화이트, 베이지, 그레이]   
361               모던리빙 모던블랑켓 대 타올이불 이불수건                       [베이지, 블루, 그레이]   
278                             린넨 이불정리함                           [그레이, 베이지]   
115  이불앞베개앞매트 면마이크로 바이오워싱가공 수 면 데니아 마이크로             [화이트, 베이지, 그레이, 옐로우, 민트]   
26                                    없음                     [아이보리, 베이지, 라벤더]   
379                                   없음                       [민트, 화이트, 내츄럴]   
9                                     없음                      [아이보리, 옐로우, 차콜]   
352      위즈홈 접이식 튼튼한 빨래건조대 프리미엄 단 더블퀸 블랙                                [베이지]   
225                       린넨폴리언더베드정리함 특대                      [베이지, 그레이, 브라운]   

    Range           color_list_literal  weighted_rating  
377    고가      옐로우 애쉬민트 화이트 베이지 그레이 차콜         4.744968  
339    고가                    베이지 카멜 차콜         4.674474  
137    고가  크림화이트 베이지 머스타드 핑크 민트 딥그린 차콜         4.647781  
131    고가      옐로우 애쉬민트 화이트 베이지 그레이 차콜         4.625876  
263    고가                아이보리 베이지 연그레이         4.615014  
159    고가         베이지 옐로우 딸기우유핑크 민트 블랙         4.563513  
235    고가                  화이트 베이지 그레이         4.505126  
361    고가                   베이지 블루 그레이         4.481775  
278    고가                      그레이 베이지         4.452704  
115    고가           화이트 베이지 그레이 옐로우 민트         4.452042  
26     고가                 아이보리 베이지 라벤더         4.426178  
379    고가                   민트 화이트 내츄럴         4.411697  
9      고가                  아이보리 옐로우 차콜         4.390684  
352    고가                          베이지         4.364608  
225    고가                  베이지 그레이 브라운         4.359605

## 소재 유사성 높은 순으로 뽑고 가중평점순으로 추천

In [164]:
goods_title = df2[df2['material'].str.contains('폴리에스터', na=False)]
goods_title = goods_title.loc[[27], : ]
goods_title

title  price  rating  review_num  \
27  노르빅 차렵이불+구름 토퍼+베개커버 세트 S/Q/K 3Color  84800     4.7          93   

                                         material color_list Range  \
27  공통 워싱 폴리에스터 전 차렵이불 토퍼 폴리에스터 밑면 토퍼 폴리에스터 논슬립가공       [없음]    고가   

   color_list_literal  weighted_rating  
27                 없음          4.39802

In [167]:
title_index = len(df2.loc[: 27, : ])
title_index-1

11

In [168]:
material_sim_sorted_ind[title_index-1]

array([ 11,  56,  90, 197,   4, 137, 168,  39, 141, 235,  86, 224,  67,
        73, 160,  14, 169, 175, 188, 258,  47, 108, 179,  85, 104,  94,
       252, 240, 194, 202, 111, 220, 251, 110, 105,  58,  21, 177, 191,
        61,  50, 152,  70,  81, 140, 233, 135, 121, 119, 144,  36, 101,
       146, 190,  65,  64, 184,  40, 245, 229, 230,  74, 127, 149, 257,
        91,  59, 118, 234,  23,  38, 100, 170,  83, 259, 112, 243,  53,
       241,  87,  92,  13,  15,  89,  88,  16,  17,  93,  18,  19,  20,
        22,  84,  24,  12,   2,   3,   8,   1,   5, 103, 102,   6,   7,
         9,  82,  99,  10,  98,  97,  96,  95,  25,  26, 106,  60,  37,
        41,  42,  43,  63,  62,  44,  45,  27,  46,  48,  49,  51,  57,
        52,  55,  35,  66,  34,  68,  80,  28,  79,  78,  29,  77,  76,
        75,  30,  31,  72,  71,  32,  33,  69,  54, 129, 107, 218, 216,
       215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203,
       201, 200, 199, 198, 196, 195, 193, 192, 189, 217, 219, 18

In [172]:
similar_indexes1 = material_sim_sorted_ind[title_index-1, :20]
similar_indexes1

array([ 11,  56,  90, 197,   4, 137, 168,  39, 141, 235,  86, 224,  67,
        73, 160,  14, 169, 175, 188, 258], dtype=int64)

In [173]:
# 추출된 top_20 index들 출력. top_20 index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경하고싶어서 (-1)을 함
similar_indexes1 = similar_indexes1.reshape(-1)
print(similar_indexes1)

[ 11  56  90 197   4 137 168  39 141 235  86 224  67  73 160  14 169 175
 188 258]


In [174]:
df3 =df2.iloc[similar_indexes1]
df3 = df3[df3['Range'].str.contains('고가', na=False)].sort_values('weighted_rating', ascending=False)[:10]
df3

title  price  rating  review_num  \
160   복숭아촉감 보드라운 피치스킨 스테이 먼지없는 차렵이불(단품) 10colors  26900     4.7        2788   
342        토파즈 60수 고밀도 워싱 차렵이불 세트 (8colors) SS/Q  49900     4.7         630   
290   복숭아촉감 보드라운 피치스킨 스테이 먼지없는 차렵이불(세트) 10colors  32900     4.6       12638   
423                  클라우드 60수광목 차렵이불(세트) 2colors  49900     4.6        2804   
381               파운드 40수 트윌 이불커버 SS/QK 12colors  18900     4.6        2303   
106                   [슈퍼세일] 옷장정리 기능성옷걸이 이불걸이 5개  10500     4.7         368   
12                      구스이불처럼 포근한 워셔블 이불솜 3size  99000     4.7         301   
304  [5%쿠폰] 샤르르 먼지없는 모달 100% 차렵이불세트 알러지케어 호텔침구세트  53800     4.7         228   
151          부드러운 메종 프릴 순면 60수 차렵이불(SS/Q)-5color  44900     4.7         195   
27           노르빅 차렵이불+구름 토퍼+베개커버 세트 S/Q/K 3Color  84800     4.7          93   

                                          material  \
160                                          폴리에스터   
342                                          폴리에스터   
290                                      면 전 폴리에스터   
423                                  폴리에스터 전 폴리에스터   
381                                  폴리에스터 전 폴리에스터   
106                                          폴리에스터   
12                                           폴리에스터   
304                                  폴리에스터 전 폴리에스터   
151                                면 폴리에스터 전 폴리에스터   
27   공통 워싱 폴리에스터 전 차렵이불 토퍼 폴리에스터 밑면 토퍼 폴리에스터 논슬립가공   

                                           color_list Range  \
160                                              [없음]    고가   
342                                              [없음]    고가   
290                                              [없음]    고가   
423                                              [없음]    고가   
381                         [머스타드, 핑크, 그린, 모카브라운, 차콜]    고가   
106  [크림, 모짜, 체다, 루프, 버블검, 오키드, 오로라, 알로하, 에어, 도브, 느와]    고가   
12                                               [없음]    고가   
304                           [캠핑이불, 아이보리, 캠핑이불, 베이지]    고가   
151                 [한정수량특가, 라이트그레이, 한정수량특가, 브릭, 베이지]    고가   
27                                               [없음]    고가   

                       color_list_literal  weighted_rating  
160                                    없음         4.678093  
342                                    없음         4.614874  
290                                    없음         4.595933  
423                                    없음         4.582245  
381                   머스타드 핑크 그린 모카브라운 차콜         4.578570  
106  크림 모짜 체다 루프 버블검 오키드 오로라 알로하 에어 도브 느와         4.568964  
12                                     없음         4.548001  
304                    캠핑이불 아이보리 캠핑이불 베이지         4.515913  
151           한정수량특가 라이트그레이 한정수량특가 브릭 베이지         4.496492  
27                                     없음         4.398020